name: Build APK with Buildozer

on:
  push:
    branches:
      - main  # Hoặc thay bằng nhánh bạn muốn trigger workflow khi push lên

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip install --upgrade pip
        pip install buildozer

    - name: Install Android dependencies
      run: |
        sudo apt-get install -y openjdk-8-jdk
        sudo apt-get install -y git
        sudo apt-get install -y unzip
        sudo apt-get install -y zlib1g-dev
        sudo apt-get install -y libncurses5
        sudo apt-get install -y libstdc++6
        sudo apt-get install -y lib32z1
        sudo apt-get install -y libbz2-dev
        sudo apt-get install -y libssl-dev

    - name: Build APK
      run: |
        cd <your-project-directory>  # Thay <your-project-directory> bằng thư mục chứa file buildozer.spec của bạn
        buildozer android debug
